const { test } = require('node:test');
const assert = require('node:assert/strict');
const { spawn, execFile } = require('node:child_process');
const { promisify } = require('node:util');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const http = require('node:http');
const { recoverDataLock } = require('../lib/data-lock');

test('real HTTP workflow, persistence, failure states and local access boundaries', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'health-api-'));
  // Ask Windows for an available port rather than guessing within an occasionally reserved range.
  async function availablePort() {
    const probe = require('node:net').createServer();
    await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve));
    const result = probe.address().port;
    await new Promise(resolve => probe.close(resolve)); return result;
  }
  const port = await availablePort();
  const base = `http://127.0.0.1:${port}`;
  let child;
  async function start() {
    child = spawn(process.execPath, [path.join(__dirname, '../server.js')], { env: { ...process.env, SONAR_TOKEN: '', PORT: String(port), HEALTH_DATA_DIR: dir }, windowsHide: true });
    await new Promise((resolve, reject) => { child.stdout.on('data', text => { if (text.toString().includes('Code Health Center:')) resolve(); }); child.stderr.on('data', text => reject(new Error(text.toString()))); });
  }
  async function stop() {
    if (child.exitCode === null) await new Promise(resolve => { child.once('exit', resolve); child.kill(); });
    // Windows process.kill may forcibly terminate Node without signal cleanup. Recover only its confirmed-dead owner.
    if (await fs.stat(path.join(dir, '.owner-lock')).then(() => true, () => false)) await recoverDataLock(dir);
  }
  t.after(async () => { await stop(); await fs.rm(dir, { recursive: true, force: true }); });
  await start();
  const call = async (endpoint, data, headers = {}) => {
    const response = await fetch(base + endpoint, data ? { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(data) } : { headers });
    return { status: response.status, body: await response.json() };
  };
  const wait = async id => {
    for (let i = 0; i < 600; i++) {
      const result = await call(`/api/scan?id=${id}`);
      if (result.body.status !== 'running') return result.body;
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    throw new Error('scan timed out');
  };
  assert.equal((await call('/api/state')).body.projects.length, 0);
  assert.equal((await call('/api/state', null, { Origin: 'http://evil.invalid' })).status, 403);
  const badHostStatus = await new Promise((resolve, reject) => {
    const req = http.get(base + '/api/state', { headers: { Host: 'evil.invalid' } }, res => { res.resume(); resolve(res.statusCode); });
    req.on('error', reject);
  });
  assert.equal(badHostStatus, 403);
  const fixture = (await call('/api/fixture')).body.path;
  const created = await call('/api/projects', { name: 'Fixture', key: 'fixture', path: fixture });
  assert.equal(created.status, 201);
  assert.equal((await call('/api/projects', { name: 'Duplicate', key: 'fixture', path: fixture })).status, 400);
  assert.equal((await call('/api/projects', { name: 'Invalid', key: 'invalid', path: dir })).status, 400);
  const item = created.body;
  assert.equal((await call(`/api/coding-brief?projectId=${item.id}`)).body.brief, null);
  assert.equal((await call('/api/coding-brief/export', { projectId: item.id })).status, 400);
  assert.equal((await call('/api/coding-brief?projectId=unknown')).status, 404);
  const brief = Object.fromEntries((await call('/api/state')).body.briefFields.map(f => [f.id, `原始约定 ${f.name}`]));
  assert.equal((await call('/api/coding-brief', { projectId: item.id, brief: { ...brief, goal: 'x'.repeat(3001) } })).status, 400);
  const savedBrief = (await call('/api/coding-brief', { projectId: item.id, brief })).body;
  assert.equal(savedBrief.ready, true);
  assert.equal((await call('/api/state')).body.projects[0].codingBrief.goal, undefined);
  const readiness = (await call('/api/preflight', { projectId: item.id, mode: 'local' })).body;
  assert.equal(readiness.ready, true);
  assert.equal((await call('/api/preflight', { projectId: item.id, mode: 'full', scope: 'changed' })).status, 400);
  assert.equal((await call('/api/projects/update', { ...item, name: 'Renamed fixture' })).status, 200);
  assert.equal((await call('/api/projects/update', { ...item, key: 'new-key' })).status, 400);
  const scan = (await call('/api/scans', { projectId: item.id, mode: 'local' })).body;
  const completed = await wait(scan.id);
  assert.equal(completed.status, 'completed');
  assert.equal(completed.issues.length, 5);
  assert.equal(completed.gate.status, 'FAILED');
  assert.equal(completed.metrics.coverage, undefined);
  assert.match(completed.logs, /不包含编译/);
  assert.equal(completed.preflight.ready, true);
  assert.equal(completed.codingBrief.id, savedBrief.brief.id);
  const updatedBrief = (await call('/api/coding-brief', { projectId: item.id, brief: { ...brief, goal: '更新后的需求' } })).body;
  assert.notEqual(updatedBrief.brief.id, savedBrief.brief.id);
  const reviewedReport = (await call(`/api/report?id=${scan.id}`)).body;
  assert.equal(reviewedReport.codingBrief.goal, brief.goal);
  assert.equal(reviewedReport.readiness.status, 'BLOCKED');
  assert.equal(reviewedReport.readiness.missing.length, 5);
  const exportedBrief = (await call('/api/coding-brief/export', { projectId: item.id })).body;
  const briefDownload = await fetch(base + exportedBrief.url);
  assert.match(briefDownload.headers.get('content-type'), /text\/markdown/);
  assert.match(await briefDownload.text(), /更新后的需求/);
  const compactState = (await call('/api/state')).body;
  assert.equal(compactState.scans[0].issueCount, 5);
  assert.equal(compactState.scans[0].issues, undefined);
  assert.equal(compactState.scans[0].logs, undefined);
  assert.equal(compactState.projectIssues, undefined);
  assert.equal(compactState.stats.issues, 5);
  const issuePage = (await call('/api/issues?limit=2')).body;
  assert.equal(issuePage.total, 5); assert.equal(issuePage.rows.length, 2);
  const remainingIssues = (await call('/api/issues?offset=4&limit=2')).body;
  assert.equal(remainingIssues.rows.length, 1);
  assert.equal((await call('/api/issues?search=List.of')).body.total, 1);
  assert.equal((await call('/api/issues?limit=101')).status, 400);
  assert.equal((await call('/api/issues?offset=-1')).status, 400);
  assert.equal((await call('/api/issues?severity=unknown')).status, 400);
  assert.equal((await call('/api/issues?projectId=unknown')).status, 404);
  const history = (await call('/api/history?limit=1')).body;
  assert.equal(history.rows.length, 1); assert.equal(history.rows[0].issues, undefined);
  assert.equal((await call('/api/history?status=failed')).body.total, 0);
  const health = (await call('/api/health')).body;
  assert.equal(health.status, 'UP'); assert.equal(health.storage.strategy, 'details-on-demand');
  assert.ok(health.memory.rssMB > 0); assert.ok(health.memory.heapMB > 0);
  assert.equal((await call(`/api/report?id=${scan.id}`)).body.issues.length, 5);
  assert.equal((await call('/api/report?id=../../state')).status, 404);
  const unchangedIndex = await fs.readFile(path.join(dir, 'state.json'), 'utf8');
  const secondOutput = await new Promise(resolve => {
    const second = spawn(process.execPath, [path.join(__dirname, '../server.js')], { env: { ...process.env, PORT: String(port), HEALTH_DATA_DIR: dir }, windowsHide: true });
    let output = ''; second.stderr.on('data', data => { output += data; }); second.on('exit', code => resolve({ code, output }));
  });
  assert.equal(secondOutput.code, 1); assert.match(secondOutput.output, /已被占用/);
  assert.equal(await fs.readFile(path.join(dir, 'state.json'), 'utf8'), unchangedIndex);
  const alternatePort = await availablePort();
  const lockedOutput = await new Promise(resolve => {
    const second = spawn(process.execPath, [path.join(__dirname, '../server.js')], { env: { ...process.env, PORT: String(alternatePort), HEALTH_DATA_DIR: dir }, windowsHide: true });
    let output = ''; second.stderr.on('data', data => { output += data; }); second.on('exit', code => resolve({ code, output }));
  });
  assert.equal(lockedOutput.code, 1); assert.match(lockedOutput.output, /数据目录已被占用/);
  assert.equal(await fs.readFile(path.join(dir, 'state.json'), 'utf8'), unchangedIndex);
  const tasks = (await call(`/api/tasks?id=${scan.id}`)).body.tasks;
  assert.equal((await call(`/api/tasks?id=${scan.id}`)).body.scan.projectId, item.id);
  const evidenceExport = (await call('/api/export', { search: 'List.of' })).body;
  assert.equal(JSON.parse(await fs.readFile(evidenceExport.path, 'utf8')).length, 1);
  assert.equal(tasks.length, 5);
  assert.equal(tasks[0].severity, 'HIGH');
  const checks = (await call('/api/state')).body.checklist;
  const acceptance = Object.fromEntries(checks.map(c => [c.id, { checked: true, evidence: '手工验证需求与异常情况均符合预期' }]));
  assert.equal((await call('/api/acceptance', { id: scan.id, acceptance })).body.status, 'BLOCKED');
  assert.equal((await call(`/api/scan?id=${scan.id}`)).body.acceptance.tests.checked, true);
  acceptance.tests.evidence = 'OK';
  assert.equal((await call('/api/acceptance', { id: scan.id, acceptance })).status, 400);
  assert.equal((await call('/api/github/token', { token: 'runtime-only-github-token' })).status, 200);
  assert.equal((await call('/api/state')).body.githubTokenConfigured, true);
  assert.ok(!(await fs.readFile(path.join(dir, 'state.json'), 'utf8')).includes('runtime-only-github-token'));
  await call('/api/github/token', { clear: true });
  assert.equal((await call('/api/state')).body.githubTokenConfigured, false);
  const taskExport = (await call('/api/export', { scanId: scan.id, kind: 'tasks' })).body;
  assert.match(await fs.readFile(taskExport.path, 'utf8'), /修复任务清单/);
  assert.match(await fs.readFile(taskExport.path, 'utf8'), /原始约定 目标与预期行为/);
  assert.match(await fs.readFile(taskExport.path, 'utf8'), /验收缺口/);
  assert.ok(!(await fs.readFile(taskExport.path, 'utf8')).includes('更新后的需求'));
  assert.match((await fetch(base + taskExport.url)).headers.get('content-type'), /text\/markdown/);
  const exported = (await call('/api/export', { scanId: scan.id })).body;
  assert.equal(JSON.parse(await fs.readFile(exported.path, 'utf8')).issues.length, 5);
  const download = await fetch(base + exported.url);
  assert.match(download.headers.get('content-disposition'), /attachment/);
  assert.equal((await download.json()).id, scan.id);
  const exportedIssues = (await call('/api/export', { projectId: item.id, severity: 'HIGH' })).body;
  assert.equal(JSON.parse(await fs.readFile(exportedIssues.path, 'utf8')).length, 3);
  assert.equal((await call('/api/baseline', { projectId: item.id, scanId: scan.id })).status, 200);
  const issue = completed.issues.find(i => i.rule === 'java8-api');
  assert.match((await call(`/api/source?project=${item.id}&file=${encodeURIComponent(issue.file)}`)).body.source, /List.of/);
  assert.notEqual((await call(`/api/source?project=${item.id}&file=${encodeURIComponent('../../server.js')}`)).status, 200);
  const settings = (await call('/api/state')).body.settings;
  assert.equal((await call('/api/settings', { settings: { ...settings, sonarUrl: 'http://example.com' } })).status, 400);
  assert.equal((await call('/api/settings', { settings: { ...settings, gate: { coverage: -1, duplication: 5 } } })).status, 400);
  assert.equal((await call('/api/settings', { settings, token: 'private-test-secret' })).status, 200);
  assert.equal((await call('/api/state')).body.tokenConfigured, true);
  assert.ok(!(await fs.readFile(path.join(dir, 'state.json'), 'utf8')).includes('private-test-secret'));
  await call('/api/settings', { settings, clearToken: true });
  const full = (await call('/api/scans', { projectId: item.id, mode: 'full' })).body;
  const failed = await wait(full.id);
  assert.equal(failed.status, 'failed');
  assert.match(failed.error, /SONAR_TOKEN/);
  const gitPath = path.join(dir, 'git-project');
  await fs.mkdir(gitPath);
  await fs.writeFile(path.join(gitPath, 'pom.xml'), '<project/>');
  await fs.writeFile(path.join(gitPath, 'A.java'), 'class A { void a() { System.out.println("old"); } }\n');
  const git = (...args) => promisify(execFile)(process.env.GIT_EXECUTABLE || 'git', ['-C', gitPath, '-c', 'user.name=Test', '-c', 'user.email=test@local', ...args], { windowsHide: true });
  await git('init'); await git('add', '.'); await git('commit', '-m', 'baseline');
  await fs.appendFile(path.join(gitPath, 'A.java'), '// TODO new\n');
  const gitProject = (await call('/api/projects', { name: 'Git project', key: 'git-project', path: gitPath })).body;
  const partial = (await call('/api/scans', { projectId: gitProject.id, mode: 'local', scope: 'changed' })).body;
  const changedReport = await wait(partial.id);
  assert.equal((await call('/api/freshness', { id: partial.id })).body.status, 'CURRENT');
  assert.equal(changedReport.issues.length, 1);
  assert.equal(changedReport.issues[0].rule, 'todo');
  assert.equal((await call('/api/baseline', { projectId: gitProject.id, scanId: partial.id })).status, 400);
  const globalIssues = (await call('/api/export', {})).body;
  assert.equal(JSON.parse(await fs.readFile(globalIssues.path, 'utf8')).length, 5);
  await git('add', '.'); await git('commit', '-m', 'clean');
  const changedBase = (await call('/api/freshness', { id: partial.id })).body;
  assert.equal(changedBase.status, 'STALE'); assert.equal(changedBase.headChanged, true);
  const clean = (await call('/api/scans', { projectId: gitProject.id, mode: 'local', scope: 'changed' })).body;
  assert.equal((await wait(clean.id)).gate.status, 'UNKNOWN');
  assert.equal((await call('/api/scans/stop', { id: 'not-running' })).status, 409);
  const slowPath = path.join(dir, 'bounded-project'); await fs.mkdir(slowPath);
  await fs.writeFile(path.join(slowPath, 'pom.xml'), '<project/>');
  // Valid large static literals keep multiple files in flight without depending on a known parser bug.
  const largeSource = 'class Slow { String text = "' + 'x'.repeat(1024 * 1024) + '"; }';
  await fs.writeFile(path.join(slowPath, 'Slow.java'), largeSource);
  for (let n = 0; n < 31; n++) await fs.writeFile(path.join(slowPath, `Slow${n}.java`), largeSource);
  const slowProject = (await call('/api/projects', { name: 'Bounded project', key: 'bounded', path: slowPath })).body;
  const stopping = (await call('/api/scans', { projectId: slowProject.id, mode: 'local' })).body;
  for (let attempt = 0; attempt < 300; attempt++) {
    const live = (await call(`/api/scan?id=${stopping.id}`)).body;
    if (live.fileProgress) break;
    await new Promise(resolve => setTimeout(resolve, 20));
    if (attempt === 299) throw new Error('Worker did not start');
  }
  assert.equal((await call('/api/health')).body.status, 'UP');
  assert.equal((await call('/api/backup', {})).status, 409);
  assert.equal((await call('/api/reports/archive', { ids: [scan.id] })).status, 409);
  assert.equal((await call('/api/scans/stop', { id: scan.id })).status, 409);
  assert.equal((await call('/api/scans/stop', { id: stopping.id })).status, 200);
  const stopped = await wait(stopping.id);
  assert.equal(stopped.status, 'failed'); assert.match(stopped.error, /已停止.*未完成/);
  assert.notEqual(stopped.gate?.status, 'PASSED');
  assert.equal((await call('/api/baseline', { projectId: slowProject.id, scanId: stopped.id })).status, 400);
  assert.equal((await call('/api/acceptance', { id: stopped.id, acceptance })).status, 400);
  await fs.writeFile(path.join(slowPath, 'Slow.java'), '// TODO\n'.repeat(10001));
  const overflowing = (await call('/api/scans', { projectId: slowProject.id, mode: 'local' })).body;
  const limited = await wait(overflowing.id);
  assert.equal(limited.status, 'failed'); assert.match(limited.error, /超过 10,000.*未完成/);
  assert.notEqual(limited.gate?.status, 'PASSED');
  const backup = await call('/api/backup', {});
  assert.equal(backup.status, 201); assert.ok(backup.body.files >= 7);
  const backupDownload = await fetch(base + backup.body.url);
  assert.equal(backupDownload.status, 200); assert.match(backupDownload.headers.get('content-type'), /gzip/);
  assert.equal((await backupDownload.arrayBuffer()).byteLength, backup.body.compressedBytes);
  let reservedRequest;
  const reservedBackup = new Promise((resolve, reject) => {
    reservedRequest = http.request(base + '/api/backup', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': 2 } }, res => { res.resume(); res.once('end', () => resolve(res.statusCode)); });
    reservedRequest.on('error', reject); reservedRequest.write('{');
  });
  try {
    for (let attempt = 0; attempt < 100; attempt++) {
      if ((await call('/api/health')).body.backupActive) break;
      await new Promise(resolve => setTimeout(resolve, 10));
      if (attempt === 99) throw new Error('Backup reservation not visible');
    }
    assert.equal((await call('/api/settings', { settings })).status, 409);
    assert.equal((await call('/api/scans', { projectId: item.id, mode: 'local' })).status, 409);
    assert.equal((await call('/api/backup', {})).status, 409);
  } finally { reservedRequest.end('}'); }
  assert.equal(await reservedBackup, 201);
  const strict = { requireBrief: false, requireFull: true, minTests: 1, blockMedium: false, gate: { coverage: 80, duplication: 3 } };
  assert.equal((await call('/api/projects/policy', { projectId: gitProject.id, policy: { ...strict, minTests: -1 } })).status, 400);
  const savedPolicy = (await call('/api/projects/policy', { projectId: gitProject.id, policy: strict })).body;
  const policyScan = (await call('/api/scans', { projectId: gitProject.id, mode: 'local' })).body;
  const policyReport = await wait(policyScan.id);
  assert.equal(policyReport.gate.status, 'UNKNOWN');
  assert.equal(policyReport.policy.id, savedPolicy.id);
  assert.equal(policyReport.settings.gate.coverage, 80);
  acceptance.tests.evidence = '手工证据仅为测试声明，不替代自动报告';
  assert.equal((await call('/api/acceptance', { id: policyScan.id, acceptance })).body.status, 'BLOCKED');
  await call('/api/projects/policy', { projectId: gitProject.id, policy: { ...strict, minTests: 0, requireFull: false, gate: null } });
  assert.equal((await call(`/api/report?id=${policyScan.id}`)).body.policy.minTests, 1);
  assert.equal((await call(`/api/report?id=${scan.id}`)).body.policy, null);
  // Archive a real older changed-scope scan, edit retained evidence, then restore without replacing latest results.
  assert.equal((await call('/api/reports/archive', { ids: [scan.id] })).status, 400);
  assert.equal((await call('/api/reports/archive', { ids: [policyScan.id] })).status, 400);
  const originalPartial = (await call(`/api/report?id=${partial.id}`)).body;
  assert.equal((await call('/api/reports/archive', { ids: [partial.id] })).status, 200);
  assert.equal((await call('/api/history?kind=archive')).body.total, 1);
  assert.deepEqual((await call(`/api/report?id=${partial.id}`)).body.issues, originalPartial.issues);
  assert.equal((await call('/api/acceptance', { id: partial.id, acceptance })).status, 200);
  assert.equal((await call('/api/history?kind=archive')).body.total, 1);
  assert.ok(!(await call('/api/state')).body.scans.some(r => r.id === partial.id));
  assert.equal((await call('/api/projects/archive', { id: gitProject.id })).status, 200);
  assert.ok((await call('/api/state')).body.projects.find(p => p.id === gitProject.id).archivedAt);
  assert.equal((await call('/api/scans', { projectId: gitProject.id, mode: 'local' })).status, 400);
  assert.equal((await call('/api/projects/restore', { id: gitProject.id })).status, 200);
  assert.equal((await call('/api/reports/restore', { id: partial.id })).status, 200);
  assert.equal((await call('/api/history?kind=archive')).body.total, 0);
  assert.equal((await call('/api/history?projectId=' + gitProject.id)).body.rows[0].id, policyScan.id);
  // A zero-finding scan is reviewable only while tracked source/configuration matches its captured version.
  const proofPath = path.join(dir, 'freshness-project'); await fs.mkdir(proofPath);
  await fs.writeFile(path.join(proofPath, 'pom.xml'), '<project/>');
  await fs.writeFile(path.join(proofPath, 'A.java'), 'class A {}');
  const proofProject = (await call('/api/projects', { name: 'Freshness', key: 'freshness', path: proofPath })).body;
  const proofScan = (await call('/api/scans', { projectId: proofProject.id, mode: 'local' })).body;
  const proofReport = await wait(proofScan.id);
  assert.equal(proofReport.gate.status, 'PASSED'); assert.equal(proofReport.sourceSnapshot.files.length, 2);
  assert.equal((await call('/api/state')).body.scans.find(r => r.id === proofScan.id).sourceSnapshot, undefined);
  assert.equal((await call('/api/acceptance', { id: proofScan.id, acceptance })).body.status, 'REVIEWED');
  await fs.writeFile(path.join(proofPath, 'A.java'), 'class B {}');
  const stale = (await call('/api/freshness', { id: proofScan.id })).body;
  assert.equal(stale.status, 'STALE'); assert.equal(stale.counts.modified, 1); assert.equal(stale.changes[0].file, 'A.java');
  assert.equal((await call('/api/acceptance', { id: proofScan.id, acceptance })).body.status, 'BLOCKED');
  const staleReport = (await call('/api/report?id=' + proofScan.id)).body;
  assert.equal(staleReport.gate.status, 'PASSED'); assert.ok(staleReport.readiness.blockers.some(value => value.includes('变化')));
  assert.equal(staleReport.acceptance.tests.checked, true);
  const freshScan = (await call('/api/scans', { projectId: proofProject.id, mode: 'local' })).body;
  await wait(freshScan.id);
  assert.equal((await call('/api/acceptance', { id: freshScan.id, acceptance })).body.status, 'REVIEWED');
  const versionExport = (await call('/api/export', { scanId: freshScan.id, kind: 'tasks' })).body;
  assert.match(await fs.readFile(versionExport.path, 'utf8'), /代码版本证据/);
  const movingPath = path.join(dir, 'moving-source'); await fs.mkdir(movingPath);
  await fs.writeFile(path.join(movingPath, 'pom.xml'), '<project/>');
  for (let n = 0; n < 500; n++) await fs.writeFile(path.join(movingPath, `A${n}.java`), 'class A {}\n// TODO\n'.repeat(10));
  const movingProject = (await call('/api/projects', { name: 'Changing during scan', key: 'moving-source', path: movingPath })).body;
  const movingScan = (await call('/api/scans', { projectId: movingProject.id, mode: 'local' })).body;
  for (let n = 0; n < 1000; n++) {
    const live = (await call('/api/scan?id=' + movingScan.id)).body;
    if (live.fileProgress && live.status === 'running') { await fs.writeFile(path.join(movingPath, 'pom.xml'), '<project><!-- changed during checks --></project>'); break; }
    if (live.status !== 'running' || n === 999) throw Error('Could not observe scan before configuration mutation');
    await new Promise(resolve => setTimeout(resolve, 2));
  }
  const movingReport = await wait(movingScan.id);
  assert.equal(movingReport.status, 'failed'); assert.match(movingReport.error, /检查期间.*变化/);
  assert.notEqual(movingReport.gate.status, 'PASSED');
  assert.equal((await call('/api/acceptance', { id: movingScan.id, acceptance })).status, 400);
  await stop(); await start();
  const restored = (await call('/api/state')).body;
  assert.equal(restored.projects[0].baselineId, scan.id);
  assert.equal(restored.scans.length, 10);
  assert.equal((await call('/api/freshness', { id: freshScan.id })).body.status, 'CURRENT');
  assert.equal(restored.tokenConfigured, false);
  assert.equal((await call(`/api/coding-brief?projectId=${item.id}`)).body.brief.id, updatedBrief.brief.id);
  assert.equal((await call(`/api/report?id=${scan.id}`)).body.codingBrief.id, savedBrief.brief.id);
  const page = await fetch(base);
  assert.match(await page.text(), /CodeHealth/);
  assert.match(page.headers.get('content-security-policy'), /frame-ancestors 'none'/);
});
